version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: notesbackend:latest
    ports:
      - "8082:8082"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: notesfrontend:latest
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8082/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
